version: 0.2

phases:
    install:
      runtime-versions:
        nodejs: 14
        python: 3.8
      commands:
        - npm install -g yarn
        - pip3 install --upgrade pip
        - pip3 install --upgrade awscliv2
        - apt install jq -y
    build:
      commands:
        - ls -al
        - tar -xzf fhirworks.tgz
        - POOL_ID=$CloudDataHubUserPoolId && echo "POOL_ID=$POOL_ID"
        - CLIENT_ID=$CloudDataHubUserPoolClientId && echo "CLIENT_ID=$CLIENT_ID"
        - echo "POOL_DOMAIN=$POOL_DOMAIN"
        - echo "STAGE_NAME=$STAGE_NAME"
        - echo "STAGE_TYPE=$STAGE_TYPE"
        - echo "REGION=$REGION"
        - echo "ALL_TENANTS_SCOPE=$ALL_TENANTS_SCOPE"
        - (cd fhirworks/fhir-works-on-aws-deployment/scripts && chmod +rx ./install.sh && ./install.sh --silentInstall "yes" --stage "$STAGE_NAME" --stagetype "$STAGE_TYPE" --region "$REGION" --pool "$POOL_ID" --poolclient "$CLIENT_ID" --pooldomain "$POOL_DOMAIN" --enableMultiTenancy --tenantIdClaimPath "cognito:groups" --corsOrigins "ALL_ORIGINS" --useApiKeys "no" --tenantIdClaimValuePrefix "quentry:" --grantAccessAllTenantsScope "$ALL_TENANTS_SCOPE")
        - cat "fhirworks/fhir-works-on-aws-deployment/Info_Output.log"
        - |
          SERVICE_ENDPOINT=$(grep 'ServiceEndpoint: ' fhirworks/fhir-works-on-aws-deployment/Info_Output.log | sed 's/^.*: //') && echo "SERVICE_ENDPOINT=$SERVICE_ENDPOINT"
          aws ssm put-parameter --name "$STAGE_NAME-fhirworks-url" --value "$SERVICE_ENDPOINT" --type "String" --overwrite
          echo "{ \"ServiceEndpoint\": \"$SERVICE_ENDPOINT\" }" > fw-deploy-output.json
        # - API_URL = $SERVICE_ENDPOINT && echo "API_URL = $SERVICE_ENDPOINT"
        # - API_KEY = "dummy" 
        # - API_AWS_REGION = $REGION && echo "API_AWS_REGION = $REGION"
        # - COGNITO_CLIENT_ID = $CLIENT_ID && echo "COGNITO_CLIENT_ID = $CLIENT_ID"
        - yarn run int-test

artifacts:
  files:
    - fhirworks/fhir-works-on-aws-deployment/Info_Output.log
    - fw-deploy-output.json

reports:
  # Binding via weak naming convention: This name is part of the ReportGroup Name, being created in the fhirworks-pipeline
  # By changing the name the binding can easily get broken see "!Join [ '-', [!Ref FhirWorksCodeBuild, !Ref FhirWorksTestReportGroupName]]" of FhirWorksCodeBuildReportGroup inside fhirworks-pipeline.yml 
  # https://docs.aws.amazon.com/codebuild/latest/userguide/test-report-group-naming.html
  # https://docs.aws.amazon.com/codebuild/latest/userguide/report-group-create.html
  fhir_works_test_report: 
    files:
     - fhir-works-on-aws-deployment-reports.xml
    file-format: JUNITXML