version: 0.2

phases:
    install:
      runtime-versions:
        nodejs: 18
      commands:
        - npm install -g yarn
        - apt install git -y
    build:
      commands:
        # AWS doesn't like symlinks, so we have to go around this
        - PACKAGE=../fhirworks

        - mkdir $PACKAGE
        - mkdir -p $PACKAGE/fhir-works-on-aws-deployment && cp -r . $PACKAGE/fhir-works-on-aws-deployment

        - echo "PACKAGE=$PACKAGE"
        - echo "FhirWorksInterfaceGitHubRepo=$FhirWorksInterfaceGitHubRepo - FhirWorksInterfaceGitHubBranch=$FhirWorksInterfaceGitHubBranch"
        - (cd $PACKAGE && git clone https://github.com/snkeos/$FhirWorksInterfaceGitHubRepo.git && cd $FhirWorksInterfaceGitHubRepo && git checkout $FhirWorksInterfaceGitHubBranch && yarn install --production && yarn run test)
        - echo "FhirWorksAuthzRBACGitHubRepo=$FhirWorksAuthzRBACGitHubRepo - FhirWorksAuthzRBACGitHubBranch=$FhirWorksAuthzRBACGitHubBranch"
        - (cd $PACKAGE && git clone https://github.com/snkeos/$FhirWorksAuthzRBACGitHubRepo.git && cd $FhirWorksAuthzRBACGitHubRepo && git checkout $FhirWorksAuthzRBACGitHubBranch && yarn install --production && yarn run test)
        - echo "FhirWorksRoutingGitHubRepo=$FhirWorksRoutingGitHubRepo - FhirWorksRoutingGitHubBranch=$FhirWorksRoutingGitHubBranch"
        - (cd $PACKAGE && git clone https://github.com/snkeos/$FhirWorksRoutingGitHubRepo.git && cd $FhirWorksRoutingGitHubRepo && git checkout $FhirWorksRoutingGitHubBranch && yarn install --production && yarn run test)
        - echo "FhirWorksSearchESGitHubRepo=$FhirWorksSearchESGitHubRepo - FhirWorksSearchESGitHubBranch=$FhirWorksSearchESGitHubBranch"
        - (cd $PACKAGE && git clone https://github.com/snkeos/$FhirWorksSearchESGitHubRepo.git && cd $FhirWorksSearchESGitHubRepo && git checkout $FhirWorksSearchESGitHubBranch && yarn install --production && yarn run test)
        - echo "FhirWorksPersistenceDDBGitHubRepo=$FhirWorksPersistenceDDBGitHubRepo - FhirWorksPersistenceDDBGitHubBranch=$FhirWorksPersistenceDDBGitHubBranch"
        - (cd $PACKAGE && git clone https://github.com/snkeos/$FhirWorksPersistenceDDBGitHubRepo.git && cd $FhirWorksPersistenceDDBGitHubRepo && git checkout $FhirWorksPersistenceDDBGitHubBranch && yarn install --production && yarn run test)

        - (cd $PACKAGE/fhir-works-on-aws-deployment && yarn install --production --verbose)
        - tar -cvzf fhirworks.tgz $PACKAGE

artifacts:
  files:
    - 'fhirworks.tgz'
    - 'buildspec-deploy.yml'

reports:
  # Binding via weak naming convention: This name is part of the ReportGroup Name, being created in the fhirworks-pipeline
  # By changing the name the binding can easily get broken see "!Join [ '-', [!Ref FhirWorksCodeBuild, !Ref FhirWorksTestReportGroupName]]" of FhirWorksCodeBuildReportGroup inside fhirworks-pipeline.yml 
  # https://docs.aws.amazon.com/codebuild/latest/userguide/test-report-group-naming.html
  # https://docs.aws.amazon.com/codebuild/latest/userguide/report-group-create.html
  fhir_works_test_report: 
    files:
     - fhir-works-on-aws-interface-reports.xml
     - fhir-works-on-aws-persistence-ddb-reports.xml
     - fhir-works-on-aws-routing-reports.xml
     - fhir-works-on-aws-authz-rbac-reports.xml
     - fhir-works-on-aws-search-es-reports.xml
    base-directory: ../fhirworks/test-reports
    file-format: JUNITXML
