version: 0.2

phases:
    install:
      runtime-versions:
        nodejs: 14
        python: 3.8
      commands:
        - env
        - npm install -g yarn
        - pip3 install --upgrade pip
        - pip3 install --upgrade awscli
    build:
      commands:
        - ls -al
        - tar -xzf fhirworks.tgz
        - (cd fhirworks/fhir-works-on-aws-deployment/scripts && ./install.sh --silentInstall "yes" --stage "$STAGE_NAME" --stagetype "$STAGE_TYPE" --region "$REGION" --pool "$POOL" --poolclient "$POOL_CLIENT" --pooldomain "$POOL_DOMAIN" --multiTenancyStrategy "UrlBased" --multiTenancyTokenClaim "cognito:groups" --corsOrigins "ALL_ORIGINS" --useApiKeys "no" --multiTenancyTokenClaimValuePrefix "quentry:")
