version: 0.2

phases:
    install:
      runtime-versions:
        python: 3.8
        nodejs: 14
      commands:
        - env
        - pip3 install --upgrade pip
        - pip3 install --upgrade awscli
        - npm install -g yarn
    build:
      commands:
        - mkdir -p fhir-works-on-aws-persistence-ddb && cp -r $CODEBUILD_SRC_DIR_FWPERSISTENCEDDB/* ./fhir-works-on-aws-persistence-ddb && mv fhir-works-on-aws-persistence-ddb ../
        - (cd ../fhir-works-on-aws-persistence-ddb && yarn install)
        - mkdir -p fhir-works-on-aws-routing && cp -r $CODEBUILD_SRC_DIR_FWROUTING/* ./fhir-works-on-aws-routing && mv fhir-works-on-aws-routing ../
        - (cd ../fhir-works-on-aws-routing && yarn install)
        - mkdir -p fhir-works-on-aws-interface && cp -r $CODEBUILD_SRC_DIR_FWINTERFACE/* ./fhir-works-on-aws-interface && mv fhir-works-on-aws-interface ../
        - (cd ../fhir-works-on-aws-interface && yarn install)

        - yarn install
        - (cd ./script && sudo ./install.sh --stage demo-cors-mt-idp --stagetype dev --region us-west-2 --pool us-west-2_BwjTcdPZY --poolclient plq1io4jmhdk54v8ugiq856lg --pooldomain demo-cog-domain --multiTenancyStrategy UrlBased --multiTenancyTokenClaim cognito:groups --multiTenancyTokenClaimValuePrefix quentry: --corsOrigins ALL_ORIGINS)