version: 0.2

phases:
    install:
      runtime-versions:
        nodejs: 14
      commands:
        - npm install -g yarn
        - apt install git -y
    build:
      commands:
        # AWS doesn't like symlinks, so we have to go around this
        - PACKAGE=../fhirworks

        - mkdir $PACKAGE
        - mkdir -p $PACKAGE/fhir-works-on-aws-deployment && cp -r . $PACKAGE/fhir-works-on-aws-deployment

        - (cd $PACKAGE && git clone https://github.com/snkeos/$FhirWorksPersistenceDDBGitHubRepo.git && cd $FhirWorksPersistenceDDBGitHubRepo && git checkout $FhirWorksPersistenceDDBGitHubBranch)
        - (cd $PACKAGE && git clone https://github.com/snkeos/$FhirWorksRoutingGitHubRepo.git && cd $FhirWorksRoutingGitHubRepo && git checkout $FhirWorksRoutingGitHubBranch)
        - (cd $PACKAGE && git clone https://github.com/snkeos/$FhirWorksInterfaceGitHubRepo.git && cd $FhirWorksInterfaceGitHubRepo && git checkout $FhirWorksInterfaceGitHubBranch)
        - (cd $PACKAGE && git clone https://github.com/snkeos/$FhirWorksSearchESGitHubRepo.git && cd $FhirWorksSearchESGitHubRepo && git checkout $FhirWorksSearchESGitHubBranch)
        - (cd $PACKAGE && git clone https://github.com/snkeos/$FhirWorksAuthzRBACGitHubRepo.git && cd $FhirWorksAuthzRBACGitHubRepo && git checkout $FhirWorksAuthzRBACGitHubBranch)

        - (cd $PACKAGE/$FhirWorksInterfaceGitHubRepo && yarn install)
        - (cd $PACKAGE/$FhirWorksAuthzRBACGitHubRepo && yarn install)
        - (cd $PACKAGE/$FhirWorksRoutingGitHubRepo && yarn install)
        - (cd $PACKAGE/$FhirWorksSearchESGitHubRepo && yarn install)
        - (cd $PACKAGE/$FhirWorksPersistenceDDBGitHubRepo && yarn install)

        - (cd $PACKAGE/fhir-works-on-aws-deployment && yarn install)
        - tar -cvzf fhirworks.tgz $PACKAGE

artifacts:
  files:
    - 'fhirworks.tgz'
    - 'buildspec-deploy.yml'
