version: 0.2

phases:
    install:
      runtime-versions:
        nodejs: 14
      commands:
        - env
        - npm install -g yarn
    build:
      commands:
        - mkdir -p fhir-works-on-aws-interface && cp -r $CODEBUILD_SRC_DIR_FWInt/* ./fhir-works-on-aws-interface && mv fhir-works-on-aws-interface ../
        - (cd ../fhir-works-on-aws-interface && yarn install)
        - mkdir -p fhir-works-on-aws-routing && cp -r $CODEBUILD_SRC_DIR_FWRout/* ./fhir-works-on-aws-routing && mv fhir-works-on-aws-routing ../
        - (cd ../fhir-works-on-aws-routing && yarn install)
        - mkdir -p fhir-works-on-aws-search-es && cp -r $CODEBUILD_SRC_DIR_FWSES/* ./fhir-works-on-aws-search-es && mv fhir-works-on-aws-search-es ../
        - (cd ../fhir-works-on-aws-search-es && yarn install)
        - mkdir -p fhir-works-on-aws-persistence-ddb && cp -r $CODEBUILD_SRC_DIR_FWPDDB/* ./fhir-works-on-aws-persistence-ddb && mv fhir-works-on-aws-persistence-ddb ../
        - (cd ../fhir-works-on-aws-persistence-ddb && yarn install)
        - yarn install
    artifacts:
      files:
        - '**/*'