version: 0.2

phases:
    install:
      runtime-versions:
        nodejs: 14
        python: 3.8
      commands:
        - npm install -g yarn
        - pip3 install --upgrade pip
        - pip3 install --upgrade awscli
        - apt install jq -y
    build:
      commands:
        - ls -al
        - tar -xzf fhirworks.tgz
        - POOL=$CloudDataHubUserPoolId && echo "POOL=$POOL"
        - POOL_CLIENT=$CloudDataHubUserPoolClientId && echo "POOL_CLIENT=$POOL_CLIENT"
        - echo "POOL_DOMAIN=$POOL_DOMAIN"
        - echo "STAGE_NAME=$STAGE_NAME"
        - echo "STAGE_TYPE=$STAGE_TYPE"
        - echo "REGION=$REGION"
        - echo "ALL_TENANTS_SCOPE=$ALL_TENANTS_SCOPE"
        - (cd fhirworks/fhir-works-on-aws-deployment/scripts && ./install.sh --silentInstall "yes" --stage "$STAGE_NAME" --stagetype "$STAGE_TYPE" --region "$REGION" --pool "$POOL" --poolclient "$POOL_CLIENT" --pooldomain "$POOL_DOMAIN" --multiTenancyEnabled --multiTenancyTokenClaim "cognito:groups" --corsOrigins "ALL_ORIGINS" --useApiKeys "no" --multiTenancyTokenClaimValuePrefix "quentry:" --multiTenancyAllTenantsScope "$ALL_TENANTS_SCOPE")
        - cat "fhirworks/fhir-works-on-aws-deployment/Info_Output.yml"
        - aws ssm put-parameter --name "$STAGE_NAME-fhirworks-url" --value "$(grep 'ServiceEndpoint: ' fhirworks/fhir-works-on-aws-deployment/Info_Output.yml | sed 's/^.*: //')" --type "String" --overwrite
        - |
          echo "{ \"ServiceEndpoint\": \"$(grep 'ServiceEndpoint: ' fhirworks/fhir-works-on-aws-deployment/Info_Output.yml | sed 's/^.*: //')\" }" > fw-deploy-output.json
artifacts:
  files:
    - fhirworks/fhir-works-on-aws-deployment/Info_Output.yml
    - fw-deploy-output.json
